// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ6ez6d75QXEd6AponFn2TTVgPNFewzII',
    appId: '1:360080836094:web:63439fa58ded1190912caf',
    messagingSenderId: '360080836094',
    projectId: 'tiktok-clone-kims97hh',
    authDomain: 'tiktok-clone-kims97hh.firebaseapp.com',
    storageBucket: 'tiktok-clone-kims97hh.appspot.com',
    measurementId: 'G-CSFXVK07YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaJ-iXCAo3sOBuH3NWoimvlC4uRR2_akM',
    appId: '1:360080836094:android:28fbc4c13eeba0fc912caf',
    messagingSenderId: '360080836094',
    projectId: 'tiktok-clone-kims97hh',
    storageBucket: 'tiktok-clone-kims97hh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZyKCYPmHQXF-C3iXUcNL99itIFThQHsw',
    appId: '1:360080836094:ios:4701e6cd8fade533912caf',
    messagingSenderId: '360080836094',
    projectId: 'tiktok-clone-kims97hh',
    storageBucket: 'tiktok-clone-kims97hh.appspot.com',
    iosClientId: '360080836094-1hofpnjqe5iqgse1vfgd452l9hl6rvqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
